services:
  - type: web
    name: gpt-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false